### ISSUE TITLE
"ci/kokoro/docker/build.sh cmake-super" hangs

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp-common#145]
```
$ ci/kokoro/docker/build.sh cmake-super
...
21/28 Test #21: optional_test .....................   Passed    0.01 sec
      Start 22: status_or_test
22/28 Test #22: status_or_test ....................   Passed    0.01 sec
      Start 23: status_test
23/28 Test #23: status_test .......................   Passed    0.00 sec
      Start 24: terminate_handler_test
24/28 Test #24: terminate_handler_test ............   Passed    0.02 sec
      Start 25: assert_ok_test
25/28 Test #25: assert_ok_test ....................   Passed    0.01 sec
      Start 26: completion_queue_test
```
then, if you interrupt it after waiting ...
```
^CCMakeFiles/google-cloud-cpp-project.dir/build.make:119: recipe for target 'build/google-cloud-cpp/src/google-cloud-cpp-project-stamp/google-cloud-cpp-project-test' failed
make[2]: *** [build/google-cloud-cpp/src/google-cloud-cpp-project-stamp/google-cloud-cpp-project-test] Interrupt
CMakeFiles/Makefile2:103: recipe for target 'CMakeFiles/google-cloud-cpp-project.dir/all' failed
make[1]: *** [CMakeFiles/google-cloud-cpp-project.dir/all] Interrupt
Makefile:83: recipe for target 'all' failed
make: *** [all] Interrupt
Build finished with 130 exit status Fri Jan 31 12:54:29 EST 2020.
```

**Comment by coryan** [comment]
You may be able to debug that by using `ci/kokoro/docker/build.sh cmake-super bash`, you should get a shell inside the Docker container.

**Comment by devbww** [comment]
Yeah, I did that.  And running `completion_queue_test`, at least, completed normally.

**Comment by coryan** [comment]
I just tested with Bazel and CMake (super build) on my workstation, ran the test by itself 1,000 times with no failures.

**Comment by devbww** [comment]
For what it's worth, @devjgm saw the same thing with `ci/kokoro/docker/build.sh cmake-super`.

**Comment by coryan** [comment]
I am able to reproduce this outside the container with:

```sh
cmake -Hsuper -Bcmake-out/su -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
cmake --build cmake-out/su
```

The test hangs with this output:

```console
./cmake-out/su/build/google-cloud-cpp/src/google-cloud-cpp-project-build/google/cloud/grpc_utils/completion_queue_test 
[==========] Running 7 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 7 tests from CompletionQueueTest
[ RUN      ] CompletionQueueTest.TimerSmokeTest
```

Using gdb I got:


```
#0  __strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:103
#1  0x00007ffff7bc1374 in grpc_core::TraceFlagList::Set(char const*, bool) () from /usr/local/google/home/coryan/common-update/cmake-out/su/external/lib/libgrpc++.so.1
#2  0x00007ffff7bc154a in grpc_tracer_init() () from /usr/local/google/home/coryan/common-update/cmake-out/su/external/lib/libgrpc++.so.1
#3  0x00007ffff78ff723 in grpc_init () from /usr/local/google/home/coryan/common-update/cmake-out/su/external/lib/libgrpc.so.9
#4  0x00005555555759fb in grpc::GrpcLibraryCodegen::GrpcLibraryCodegen(bool) ()
#5  0x00007ffff7fc89a7 in google::cloud::grpc_utils::v0::CompletionQueue::CompletionQueue() ()
   from /usr/local/google/home/coryan/common-update/cmake-out/su/build/google-cloud-cpp/src/google-cloud-cpp-project-build/google/cloud/grpc_utils/libgoogle_cloud_cpp_grpc_utils.so.0
#6  0x000055555556af7f in google::cloud::grpc_utils::v0::(anonymous namespace)::CompletionQueueTest_TimerSmokeTest_Test::TestBody() ()
#7  0x00007ffff7f6c5cd in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
   from /usr/local/google/home/coryan/common-update/cmake-out/su/external/lib/libgtest.so
#8  0x00007ffff7f613ee in testing::Test::Run() () from /usr/local/google/home/coryan/common-update/cmake-out/su/external/lib/libgtest.so
#9  0x00007ffff7f61545 in testing::TestInfo::Run() () from /usr/local/google/home/coryan/common-update/cmake-out/su/external/lib/libgtest.so
#10 0x00007ffff7f6163d in testing::TestSuite::Run() () from /usr/local/google/home/coryan/common-update/cmake-out/su/external/lib/libgtest.so
#11 0x00007ffff7f61bb3 in testing::internal::UnitTestImpl::RunAllTests() () from /usr/local/google/home/coryan/common-update/cmake-out/su/external/lib/libgtest.so
#12 0x00007ffff7f61de8 in testing::UnitTest::Run() () from /usr/local/google/home/coryan/common-update/cmake-out/su/external/lib/libgtest.so
#13 0x00007ffff7fbd48f in main () from /usr/local/google/home/coryan/common-update/cmake-out/su/build/google-cloud-cpp/src/google-cloud-cpp-project-build/google/cloud/testing_util/libgoogle_cloud_cpp_testing.so
#14 0x00007ffff71dabbb in __libc_start_main (main=0x7ffff7fbd470 <main>, argc=1, argv=0x7fffffffddc8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffddb8)
    at ../csu/libc-start.c:308
#15 0x000055555556438a in _start ()
(gdb) thread 2
[Switching to thread 2 (Thread 0x7ffff6b8e700 (LWP 23966))]
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x5555555d8410) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
88	../sysdeps/unix/sysv/linux/futex-internal.h: No such file or directory.
(gdb) bt
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x5555555d8410) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x5555555d83b0, cond=0x5555555d83e8) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x5555555d83e8, mutex=0x5555555d83b0) at pthread_cond_wait.c:655
#3  0x00007ffff70d66f3 in gpr_cv_wait () from /usr/local/google/home/coryan/common-update/cmake-out/su/external/lib/../lib/libgpr.so.9
#4  0x00007ffff7b8ce48 in grpc_core::Executor::ThreadMain(void*) () from /usr/local/google/home/coryan/common-update/cmake-out/su/external/lib/libgrpc++.so.1
#5  0x00007ffff70d8908 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::{lambda(void*)#1}::_FUN(void*) () from /usr/local/google/home/coryan/common-update/cmake-out/su/external/lib/../lib/libgpr.so.9
#6  0x00007ffff7840fb7 in start_thread (arg=<optimized out>) at pthread_create.c:486
#7  0x00007ffff72ae2ef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) thread 3
[Switching to thread 3 (Thread 0x7fffee38d700 (LWP 23967))]
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x5555555d93e0) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
88	in ../sysdeps/unix/sysv/linux/futex-internal.h
(gdb) bt
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x5555555d93e0) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x5555555d9380, cond=0x5555555d93b8) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x5555555d93b8, mutex=0x5555555d9380) at pthread_cond_wait.c:655
#3  0x00007ffff70d66f3 in gpr_cv_wait () from /usr/local/google/home/coryan/common-update/cmake-out/su/external/lib/../lib/libgpr.so.9
#4  0x00007ffff7b8ce48 in grpc_core::Executor::ThreadMain(void*) () from /usr/local/google/home/coryan/common-update/cmake-out/su/external/lib/libgrpc++.so.1
#5  0x00007ffff70d8908 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::{lambda(void*)#1}::_FUN(void*) () from /usr/local/google/home/coryan/common-update/cmake-out/su/external/lib/../lib/libgpr.so.9
#6  0x00007ffff7840fb7 in start_thread (arg=<optimized out>) at pthread_create.c:486
#7  0x00007ffff72ae2ef in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

This is reminiscent of grpc/grpc#21280, and since this repository is using gRPC-1.26.0 with super builds, I am going to say that is actually the bug. Will test with gRPC-1.27.0-pre* and see if that fixes the issue.

**Comment by coryan** [comment]
Well, 1.27.0 requires Abseil, that is more work that I am willing to do right now, specially since 1.26.x (the branch, no specific release) does include the fixes for that bug.

**Comment by coryan** [comment]
It passed on the first try.
